--  tbl_z_demo_product definition

CREATE TABLE `tbl_z_demo_product` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` varchar(32) CHARACTER SET utf8 NOT NULL COMMENT '产品名称',
  `PRODUCT_NO` varchar(32) CHARACTER SET utf8 NOT NULL COMMENT '产品编号',
  `PRODUCT_INIT_QUANTITY` bigint(20) NOT NULL COMMENT '初始库存',
  `PRODUCT_DESC` varchar(1000) CHARACTER SET utf8 DEFAULT NULL COMMENT '产品描述',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `PRODUCT_CUR_QUANITYT` bigint(20) NOT NULL DEFAULT '0' COMMENT '已经消耗库存',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `tbl_z_demo_inventory_PRODUCT_NO_IDX` (`PRODUCT_NO`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='库存信息表';

--  tbl_z_demo_transaction definition

CREATE TABLE `tbl_z_demo_transaction` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USER_Id` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户ID',
  `USER_NAME` varchar(32) CHARACTER SET utf8 NOT NULL COMMENT '用户产品名称',
  `REQUEST_SEQ` varchar(32) CHARACTER SET utf8 NOT NULL COMMENT '请求流水',
  `REQUEST_TIME` varchar(32) CHARACTER SET utf8 NOT NULL COMMENT '请求时间',
  `PRODUCT_BATCH_SERIAL_NUM` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '抽奖批次信息',
  `PRODUCT_No` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户ID',
  `RESULT` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '抽奖结果',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `RPODUCT_PRO_QUANTITY` bigint(20) DEFAULT NULL COMMENT '该笔交易扣减前已消耗库存',
  `PRODUCT_TRA_QUANTITY` bigint(20) DEFAULT NULL COMMENT '本次交易获取到的库存数量',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `tbl_z_demo_transaction_RPODUCT_PRO_QUANTITY_IDX` (`RPODUCT_PRO_QUANTITY`,`PRODUCT_No`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='交易信息表';
